### ISSUE TITLE
Italic Support

### ISSUE THREAD

**Issue by Jamerrone** [arthurwhite/white-theme-vscode#1]
Hey, could you please add support for italic fonts like Operator Mono?

**Comment by arthurwhite** [comment]
Hi,

As for colors or ligatures, I don't think italics are in the "spirit" of this theme.

But if you personally want this, you can set your own styling rules in your `settings.json`file.
For example, you can have `comments` and `keywords` in italic:
```JSON
"editor.tokenColorCustomizations": {
    "comments": {
        "fontStyle": "italic"
    },
    "keywords": {
        "fontStyle": "italic"
    }
}
```
This will take precedence over all theme rules.
