### ISSUE TITLE
Support for inverted tabs color

### ISSUE THREAD

**Issue by oscarmcm** [arthurwhite/white-theme-vscode#2]
Would be cool if we can add an option for inverted tabs color, so instead of `white` background color on dark theme, these should be `dark`

**Comment by arthurwhite** [comment]
Do you mean something like this ?

![capture d ecran 2018-03-20 a 22 49 53](https://user-images.githubusercontent.com/9503891/37684700-2b58f3e0-2c91-11e8-9ceb-c6225b4be868.png)

**Comment by oscarmcm** [comment]
Yeah, something like that would be cool

**Comment by arthurwhite** [comment]
So you can just add this to your `settings.json` file:

```json
"workbench.colorCustomizations": {
  "[White Night]": {
    "tab.activeBackground": "#000",
    "tab.activeForeground": "#fff",
  }
},
```

Making a custom configuration key would be [overcomplicated](https://code.visualstudio.com/docs/extensions/example-language-server#_explaining-the-client).

**Comment by oscarmcm** [comment]
Whoah, that was superb 👏thank you
have u plans to add apex like tabs?
![image](https://user-images.githubusercontent.com/2553459/37718935-7823f69a-2ce9-11e8-93d2-99cd112a6184.png)
with these minimal border color and variations?

**Comment by arthurwhite** [comment]
I'd like to!

But actually, VS Code only allows color tweaking.
Without a full control over the CSS, it's impossible. 😕

**Comment by oscarmcm** [comment]
I just found [`"tab.activeBorder"`](https://github.com/Microsoft/vscode/issues/29333) so I ended with something like this
```json
"[White]": {
            "tab.activeBackground": "#fff",
            "tab.activeForeground": "#000",
            "tab.activeBorder": "#000"
        },
```
![image](https://user-images.githubusercontent.com/2553459/37729080-a12c72ca-2d01-11e8-835d-0e3fdf84fc67.png)

**Comment by arthurwhite** [comment]
Personally, I think this 1px border is too thin.
I'll wait for full customization capabilities before doing it. ⏳
