### ISSUE TITLE
Rust suport missing

### ISSUE THREAD

**Issue by yelfathi** [arthurwhite/white-theme-vscode#3]
Hi please see the below screenshots between White and Verdandi theme (fct and enum keywords missing):

![white](https://user-images.githubusercontent.com/9952320/48020479-4b250100-e136-11e8-8099-9708164a0033.png)

![verdandi](https://user-images.githubusercontent.com/9952320/48020486-4eb88800-e136-11e8-8728-d490739c0976.png)

Thanks!

**Comment by yelfathi** [comment]
Apparently by adding keyword to the scope it solves the issue.

**Comment by arthurwhite** [comment]
Done!  
I published version 1.3.0.

If I missed some keywords, let me know.
